## Tensorflow Introduction

## Install `tensorflow`

In [5]:
!pip install -U tensorflow

  Obtaining dependency information for tensorflow from https://files.pythonhosted.org/packages/80/6f/57d36f6507e432d7fc1956b2e9e8530c5c2d2bfcd8821bcbfae271cd6688/tensorflow-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for tensorflow-intel==2.14.0 from https://files.pythonhosted.org/packages/ad/6e/1bfe367855dd87467564f7bf9fa14f3b17889988e79598bc37bf18f5ffb6/tensorflow_intel-2.14.0-cp311-cp311-win_amd64.whl.metadata
  Obtaining dependency information for absl-py>=1.0.0 from https://files.pythonhosted.org/packages/01/e4/dc0a1dcc4e74e08d7abedab278c795eef54a224363bb18f5692f416d834f/absl_py-2.0.0-py3-none-any.whl.metadata
  Obtaining dependency information for flatbuffers>=23.5.26 from https://files.pythonhosted.org/packages/6f/12/d5c79ee252793ffe845d58a913197bfa02ae9a0b5c9bc3dc4b58d477b9e7/flatbuffers-23.5.26-py2.py3-none-any.whl.metadata
  Using cached flatbuffers-23.5.26-py2.py3-none-any.whl.metadata (850 bytes)
     ----------------------------------------

## Import `tensorflow`

In [6]:
import tensorflow as tf    # importing tensorflow libraries

In [7]:
tf.__version__

'2.14.0'

## Using `tensorflow` library

1. Creating tensors using `constant` method.

In [9]:
hello = tf.constant("Hello World !!")  
print(hello.numpy())                

b'Hello World !!'


2. Performing operations on tensors.

In [10]:
# creating nodes in computation graph 
node1 = tf.constant(3, dtype=tf.int32)   # creates a data node 
node2 = tf.constant(5, dtype=tf.int32)   # creates a data node
node3 = tf.add(node1, node2)             # creates a function node


# evaluating node3 and printing the result 
print("Sum of node1 and node2 is:",node3.numpy()) 

Sum of node1 and node2 is: 8


3. Creating tensors from existing objects.

In [12]:
tf_t = tf.convert_to_tensor(5.0, dtype=tf.float64) 

In [13]:
print(tf.rank(tf_t))
print(tf.shape(tf_t))   # pl. note, the number after Rank_ and Shape_ are internal indices. 

print(tf.rank(tf_t))    #Note: if we do not use tfs.run(), the tf.rank will only describe the node
print(tf.shape(tf_t) )  # pl. note, the number after Rank_ and Shape_ are internal indices. 

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([], shape=(0,), dtype=int32)


4. Creating tensors from 1-dimensional arrays

In [14]:
import numpy as np

one_dim_array = ([1], [2], [3], [4], [5])
print("one_dim_array Shape : ", one_dim_array)

tf_t = tf.convert_to_tensor(one_dim_array, dtype=tf.float64)
print('\n')
print(tf_t)
print('rank of tf_t : ', tf.rank(tf_t))     #Note: if we do not use tfs.run(), the tf.rank will only describe the node
print('shape of tf_t: ', tf.shape(tf_t))
print('\n')
print('tf_t[0] : ', tf_t[0])
print('tf_t[0] : ', tf_t[2])
print('\n')
print('run(tf_t) : \n', tf_t)

one_dim_array Shape :  ([1], [2], [3], [4], [5])


tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float64)
rank of tf_t :  tf.Tensor(2, shape=(), dtype=int32)
shape of tf_t:  tf.Tensor([5 1], shape=(2,), dtype=int32)


tf_t[0] :  tf.Tensor([1.], shape=(1,), dtype=float64)
tf_t[0] :  tf.Tensor([3.], shape=(1,), dtype=float64)


run(tf_t) : 
 tf.Tensor(
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]], shape=(5, 1), dtype=float64)
