In [4]:
import numpy as np
np.set_printoptions(suppress=True)

## Matrix addition, subtraction and multiplication

In [9]:
matrix_one = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_two = np.array([[10,11,12],[13,14,15],[16,17,18]])

print(f"A = {matrix_one}")
print(f"B = {matrix_two}")
print(f"A+B = {matrix_one + matrix_two}")
print(f"A-B = {matrix_one - matrix_two}")
print(f"A*B = {matrix_one * matrix_two}")


A = [[1 2 3]
 [4 5 6]
 [7 8 9]]
B = [[10 11 12]
 [13 14 15]
 [16 17 18]]
A+B = [[11 13 15]
 [17 19 21]
 [23 25 27]]
A-B = [[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
A*B = [[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]


## Checking if the matrix is invertible.

In [10]:
M=np.array([[1,2,1],[2,1,0],[3,0,2]])
print("Matrix M = ")
print(M)
a=np.linalg.det(M)
print("Determinant = ",a)
if(a!=0):
    i=np.linalg.inv(M)
    print("Inverse of Matrix M = ")
    print(i)
else:
    print("Matrix M is invertible")

Matrix M = 
[[1 2 1]
 [2 1 0]
 [3 0 2]]
Determinant =  -8.999999999999998
Inverse of Matrix M = 
[[-0.22222222  0.44444444  0.11111111]
 [ 0.44444444  0.11111111 -0.22222222]
 [ 0.33333333 -0.66666667  0.33333333]]


In [11]:
M=np.array([[5,7],[2,3]])
print("Matrix M = ")
print(M)
a=np.linalg.det(M)
print("Determinant = ",a)
if(a!=0):
    i=np.linalg.inv(M)
    print("Inverse of Matrix M = ")
    print(i)
else:
    print("Matrix M is invertible")

Matrix M = 
[[5 7]
 [2 3]]
Determinant =  0.9999999999999987
Inverse of Matrix M = 
[[ 3. -7.]
 [-2.  5.]]
